from enum import Enum

class EnvironmentEnum(str, Enum):
    TEST = "TEST"
    DEMO = "DEMO"

class CaseStateEnum(str, Enum):
    NEW = "NEW"
    INGESTED = "INGESTED"
    RISK_DETECTED = "RISK_DETECTED"
    DIAGNOSED = "DIAGNOSED"
    RECOMMENDATION_READY = "RECOMMENDATION_READY"
    POLICY_CHECK = "POLICY_CHECK"
    WAIT = "WAIT"
    BLOCKED = "BLOCKED"
    ESCALATED = "ESCALATED"
    EXECUTING = "EXECUTING"
    RECOVERED = "RECOVERED"
    FAILED = "FAILED"
    STOPPED = "STOPPED"

class PriorityEnum(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class DiagnosisCategoryEnum(str, Enum):
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    EXPIRED_PAYMENT_METHOD = "EXPIRED_PAYMENT_METHOD"
    REPEATED_DECLINE = "REPEATED_DECLINE"
    MANDATE_OR_CUSTOMER_ACTION_REQUIRED = "MANDATE_OR_CUSTOMER_ACTION_REQUIRED"
    TRANSIENT_TECHNICAL_FAILURE = "TRANSIENT_TECHNICAL_FAILURE"
    RETRY_BUDGET_EXHAUSTED = "RETRY_BUDGET_EXHAUSTED"
    UNKNOWN_OR_UNRESOLVED = "UNKNOWN_OR_UNRESOLVED"

class ActionTypeEnum(str, Enum):
    RETRY_LATER = "RETRY_LATER"
    PAYMENT_METHOD_RECOVERY = "PAYMENT_METHOD_RECOVERY"
    CUSTOMER_OUTREACH = "CUSTOMER_OUTREACH"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    WAIT = "WAIT"
    STOP = "STOP"

class PolicyDecisionEnum(str, Enum):
    ALLOW = "ALLOW"
    WAIT = "WAIT"
    BLOCK = "BLOCK"
    ESCALATE = "ESCALATE"

class ExecutionModeEnum(str, Enum):
    RAZORPAY_TEST = "RAZORPAY_TEST"
    SIMULATION = "SIMULATION"

class OutcomeTypeEnum(str, Enum):
    OBSERVED = "OBSERVED"
    SIMULATED = "SIMULATED"
    PROJECTED = "PROJECTED"
    NONE = "NONE"

class ActionStatusEnum(str, Enum):
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"
    WAITING = "WAITING"
    EXECUTING = "EXECUTING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

class ContactChannelEnum(str, Enum):
    EMAIL = "EMAIL"
    SMS = "SMS"
    WHATSAPP = "WHATSAPP"
    IN_APP = "IN_APP"
    NONE = "NONE"

class ConsentStateEnum(str, Enum):
    UNKNOWN = "UNKNOWN"
    CONSENTED = "CONSENTED"
    WITHDRAWN = "WITHDRAWN"

class SuppressionStateEnum(str, Enum):
    NONE = "NONE"
    DND = "DND"
    MERCHANT_BLOCKED = "MERCHANT_BLOCKED"
    SYSTEM_BLOCKED = "SYSTEM_BLOCKED"
